package gr.A4.SmartHouseBuilder.service;

import org.springframework.stereotype.Service;

import java.text.Normalizer;
import java.util.Set;
import java.util.regex.Pattern;

@Service
public class BadWordFilterService {
    private static final Set<String> BAD_WORDS = Set.of(
            "badword",
            "cuvantinterzis",
            "insulta",
            "2g1c",
            "2 girls 1 cup",
            "acrotomophilia",
            "alabama hot pocket",
            "alaskan pipeline",
            "anal",
            "anilingus",
            "apeshit",
            "arsehole",
            "ass",
            "asshole",
            "assmunch",
            "auto erotic",
            "autoerotic",
            "babeland",
            "baby batter",
            "baby juice",
            "ball gag",
            "ball gravy",
            "ball kicking",
            "ball licking",
            "ball sack",
            "ball sucking",
            "bangbros",
            "bareback",
            "barely legal",
            "barenaked",
            "bastard",
            "bastardo",
            "bastinado",
            "bbw",
            "bdsm",
            "beaner",
            "beaners",
            "beaver cleaver",
            "beaver lips",
            "bestiality",
            "big black",
            "big breasts",
            "big knockers",
            "big tits",
            "bimbos",
            "birdlock",
            "bitch",
            "bitches",
            "black cock",
            "blonde action",
            "blonde on blonde action",
            "blowjob",
            "blow job",
            "blow your load",
            "blue waffle",
            "blumpkin",
            "bollocks",
            "bondage",
            "boner",
            "boob",
            "boobs",
            "booty call",
            "brown showers",
            "brunette action",
            "bukkake",
            "bulldyke",
            "bullet vibe",
            "bullshit",
            "bung hole",
            "bunghole",
            "busty",
            "butt",
            "buttcheeks",
            "butthole",
            "camel toe",
            "camgirl",
            "camslut",
            "camwhore",
            "carpet muncher",
            "carpetmuncher",
            "chocolate rosebuds",
            "circlejerk",
            "cleveland steamer",
            "clit",
            "clitoris",
            "clover clamps",
            "clusterfuck",
            "cock",
            "cocks",
            "coprolagnia",
            "coprophilia",
            "cornhole",
            "coon",
            "coons",
            "creampie",
            "cum",
            "cumming",
            "cunnilingus",
            "cunt",
            "darkie",
            "date rape",
            "daterape",
            "deep throat",
            "deepthroat",
            "dendrophilia",
            "dick",
            "dildo",
            "dingleberry",
            "dingleberries",
            "dirty pillows",
            "dirty sanchez",
            "doggie style",
            "doggiestyle",
            "doggy style",
            "doggystyle",
            "dog style",
            "dolcett",
            "domination",
            "dominatrix",
            "dommes",
            "donkey punch",
            "double dong",
            "double penetration",
            "dp action",
            "dry hump",
            "dvda",
            "eat my ass",
            "ecchi",
            "ejaculation",
            "erotic",
            "erotism",
            "escort",
            "eunuch",
            "faggot",
            "fecal",
            "felch",
            "fellatio",
            "feltch",
            "female squirting",
            "femdom",
            "figging",
            "fingerbang",
            "fingering",
            "fisting",
            "foot fetish",
            "footjob",
            "frotting",
            "fuck",
            "fuck buttons",
            "fuckin",
            "fucking",
            "fucktards",
            "fudge packer",
            "fudgepacker",
            "futanari",
            "gang bang",
            "gay sex",
            "genitals",
            "giant cock",
            "girl on",
            "girl on top",
            "girls gone wild",
            "goatcx",
            "goatse",
            "god damn",
            "gokkun",
            "golden shower",
            "goodpoop",
            "goo girl",
            "goregasm",
            "grope",
            "group sex",
            "g-spot",
            "guro",
            "hand job",
            "handjob",
            "hard core",
            "hardcore",
            "hentai",
            "homoerotic",
            "honkey",
            "hooker",
            "hot carl",
            "hot chick",
            "how to kill",
            "how to murder",
            "huge fat",
            "humping",
            "intercourse",
            "jack off",
            "jail bait",
            "jailbait",
            "jelly donut",
            "jerk off",
            "jigaboo",
            "jiggaboo",
            "jiggerboo",
            "jizz",
            "juggs",
            "kike",
            "kinbaku",
            "kinkster",
            "kinky",
            "knobbing",
            "leather restraint",
            "leather straight jacket",
            "lemon party",
            "lolita",
            "lovemaking",
            "make me come",
            "male squirting",
            "masturbate",
            "menage a trois",
            "milf",
            "missionary position",
            "motherfucker",
            "mound of venus",
            "mr hands",
            "muff diver",
            "muffdiving",
            "nambla",
            "nawashi",
            "negro",
            "neonazi",
            "nigga",
            "nigger",
            "nig nog",
            "nimphomania",
            "nipple",
            "nipples",
            "nsfw images",
            "nude",
            "nudity",
            "nympho",
            "nymphomania",
            "octopussy",
            "omorashi",
            "one cup two girls",
            "one guy one jar",
            "orgy",
            "paedophile",
            "paki",
            "panties",
            "panty",
            "pedobear",
            "pedophile",
            "pegging",
            "penis",
            "phone sex",
            "piece of shit",
            "pissing",
            "piss pig",
            "pisspig",
            "playboy",
            "pleasure chest",
            "pole smoker",
            "ponyplay",
            "poof",
            "poon",
            "poontang",
            "punany",
            "poop chute",
            "poopchute",
            "porn",
            "porno",
            "pornography",
            "prince albert piercing",
            "pthc",
            "pubes",
            "pussy",
            "queaf",
            "queef",
            "quim",
            "raghead",
            "raging boner",
            "rape",
            "raping",
            "rapist",
            "rectum",
            "reverse cowgirl",
            "rimjob",
            "rimming",
            "rosy palm",
            "rosy palm and her 5 sisters",
            "rusty trombone",
            "sadism",
            "santorum",
            "scat",
            "schlong",
            "scissoring",
            "semen",
            "sex",
            "sexo",
            "sexy",
            "shaved beaver",
            "shaved pussy",
            "shemale",
            "shibari",
            "shit",
            "shitblimp",
            "shitty",
            "shota",
            "shrimping",
            "skeet",
            "slanteye",
            "slut",
            "s&m",
            "smut",
            "snatch",
            "snowballing",
            "sodomize",
            "sodomy",
            "spic",
            "splooge",
            "splooge moose",
            "spooge",
            "spread legs",
            "spunk",
            "strap on",
            "strapon",
            "strappado",
            "strip club",
            "style doggy",
            "suck",
            "sucks",
            "suicide girls",
            "sultry women",
            "swastika",
            "swinger",
            "tainted love",
            "taste my",
            "tea bagging",
            "threesome",
            "throating",
            "tied up",
            "tight white",
            "tit",
            "tits",
            "titties",
            "titty",
            "tongue in a",
            "topless",
            "tosser",
            "towelhead",
            "tranny",
            "tribadism",
            "tub girl",
            "tubgirl",
            "tushy",
            "twat",
            "twink",
            "twinkie",
            "two girls one cup",
            "undressing",
            "upskirt",
            "urethra play",
            "urophilia",
            "vagina",
            "venus mound",
            "vibrator",
            "violet wand",
            "vorarephilia",
            "voyeur",
            "vulva",
            "wank",
            "wetback",
            "wet dream",
            "white power",
            "wrapping men",
            "wrinkled starfish",
            "xx",
            "xxx",
            "yaoi",
            "yellow showers",
            "yiffy",
            "zoophilia",
            "🖕",
            "pula",
            "pizda",
            "muie",
            "fut",
            "futa",
            "fute",
            "futut",
            "fututa",
            "fututi",
            "futu",
            "futu ti",
            "fututi mortii",
            "futu ti mortii",
            "futu ti dumnezeii",
            "futu ti crucea",
            "futu ti gura",
            "futu ti rasa",
            "futu ti neamul",
            "futu ti familia",
            "futu ti pastele",
            "futu ti biserica",
            "bag pula",
            "baga mi as pula",
            "baga mi as",
            "sa mi bag pula",
            "sa ti bag pula",
            "imi bag pula",
            "iti bag pula",
            "pula mea",
            "pula mea mare",
            "sugi pula",
            "suge pula",
            "suge o",
            "sugi o",
            "suge mi o",
            "sugi mi o",
            "sugi pula mea",
            "suge pula mea",
            "sugator",
            "sugatoare",
            "pulan",
            "pulica",
            "puloi",
            "pizda ma tii",
            "pizda matii",
            "pizda ma sii",
            "pizda masii",
            "pizda ta",
            "pizdos",
            "pizdo",
            "pizde",
            "pizdulica",
            "coaie",
            "coi",
            "coios",
            "coaie mele",
            "ma doare in pula",
            "ma doare n pula",
            "ma doare in cur",
            "cur",
            "curva",
            "curve",
            "curvar",
            "curvara",
            "tarfa",
            "tarfe",
            "panarama",
            "panarame",
            "zdreanta",
            "zdreanto",
            "zdreante",
            "javra",
            "javro",
            "javre",
            "jeg",
            "jegoasa",
            "jegos",
            "nenorocit",
            "nenorocita",
            "nenorocitii",
            "bou",
            "boi",
            "vita",
            "vaca",
            "prost",
            "proasta",
            "prostule",
            "proasto",
            "cretin",
            "cretina",
            "cretino",
            "idiot",
            "idioata",
            "idiotule",
            "idioato",
            "handicapat",
            "handicapata",
            "retardat",
            "retardata",
            "imbecil",
            "imbecila",
            "dobitoc",
            "dobitoaco",
            "dobitoaca",
            "tampit",
            "tampita",
            "tampito",
            "tampenie",
            "mars",
            "mars ma",
            "mars in pula mea",
            "du te dracu",
            "du te dracului",
            "du te naibii",
            "du te in ma ta",
            "du te n ma ta",
            "du te in pizda ma tii",
            "du te in pula mea",
            "dracu",
            "dracului",
            "naibii",
            "fir ai al dracu",
            "fir ai a dracu",
            "firar al dracu",
            "firar a dracu",
            "morti",
            "mortii",
            "mortii tai",
            "mortii ma tii",
            "mortii matii",
            "mortii masii",
            "dumnezeii ma tii",
            "dumnezeii matii",
            "dumnezeii tai",
            "crucea ma tii",
            "crucea matii",
            "pastele ma tii",
            "pastele matii",
            "biserica ma tii",
            "biserica matii",
            "ma ta",
            "mata",
            "ma tii",
            "matii",
            "masii",
            "morti ma tii",
            "morti matii",
            "morti masii",
            "cacat",
            "caca",
            "cacanar",
            "cacacioasa",
            "cacacios",
            "rahat",
            "rahatule",
            "mananca cacat",
            "mananci cacat",
            "mananci rahat",
            "manca mi ai",
            "manca mi ai pula",
            "manca mi ai curu",
            "lingi curu",
            "linge curu",
            "linge ma in cur",
            "limbist",
            "limbista",
            "labar",
            "labagiu",
            "labagioaica",
            "laba",
            "fac laba",
            "muist",
            "muista",
            "muisti",
            "muie tie",
            "ia muie",
            "mars la muie",
            "muie ma",
            "muie ba",
            "muie psd",
            "muie pnl",
            "futut in cur",
            "fute te",
            "fute ma",
            "fute ti",
            "fute ti gura",
            "fute ti mortii",
            "fute ti rasa",
            "pornografie",
            "pornache",
            "masturbare",
            "masturbez",
            "masturbezi",
            "labareala",
            "orgasm",
            "vagin",
            "anus",
            "oral",
            "sperma",
            "ejaculare",
            "viol",
            "violator",
            "pedofil",
            "pedofila",
            "pedofilie",
            "incest",
            "negru imputit",
            "cioara",
            "tigan imputit",
            "tiganca imputita",
            "bozgor",
            "jidan",
            "jidanca",
            "homalau",
            "poponar",
            "lesbianca imputita"
    );

    public boolean containsBadWords(String text) {
        if (text == null || text.isBlank()) {
            return false;
        }

        String normalizedText = normalize(text);

        for (String badWord : BAD_WORDS) {
            String normalizedBadWord = normalize(badWord);
            Pattern pattern = Pattern.compile("(^|\\s)" + Pattern.quote(normalizedBadWord) + "($|\\s)");
            if (pattern.matcher(normalizedText).find()) {
                return true;
            }
        }

        return false;
    }

    private String normalize(String text) {
        String normalized = Normalizer.normalize(text, Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "")
                .toLowerCase();

        return normalized
                .replaceAll("[^a-z0-9]+", " ")
                .trim();
    }
}