sonar.projectKey=Ingineria-Programarii-SmartHouseBuilder_smart-house-builder
sonar.projectName=Smart House Builder
sonar.sourceEncoding=UTF-8

sonar.sources=Backend/src/main,Frontend/src
sonar.tests=Backend/src/test,Frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**,**/Terraform/**,**/*.d.ts
sonar.test.inclusions=Backend/src/test/**/*.java,Frontend/src/**/*.test.js,Frontend/src/**/*.test.jsx,Frontend/src/**/*.test.ts,Frontend/src/**/*.test.tsx
sonar.coverage.exclusions=Frontend/src/**/*.test.js,Frontend/src/**/*.test.jsx,Frontend/src/**/*.test.ts,Frontend/src/**/*.test.tsx,Frontend/src/test/**

sonar.java.binaries=Backend/target/classes
sonar.java.test.binaries=Backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=Backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info
sonar.organization=ingineria-programarii-smarthousebuilder
