spring.application.name=SmartHouseBuilder
server.port=20025
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-2.5-flash
spring.profiles.active=dev