package gr.A4.SmartHouseBuilder.team2.dto;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for Lombok @Data DTOs introduced in this PR.
 * Covers getters, setters, equals, hashCode, and toString generated by Lombok.
 */
class DtoTest {

    // ── PointDTO ──────────────────────────────────────────────────────────────

    @Test
    void pointDTO_gettersAndSetters() {
        PointDTO point = new PointDTO();
        point.setX(3.5);
        point.setY(7.2);

        assertThat(point.getX()).isEqualTo(3.5);
        assertThat(point.getY()).isEqualTo(7.2);
    }

    @Test
    void pointDTO_equalsAndHashCode() {
        PointDTO p1 = new PointDTO();
        p1.setX(1.0);
        p1.setY(2.0);

        PointDTO p2 = new PointDTO();
        p2.setX(1.0);
        p2.setY(2.0);

        assertThat(p1).isEqualTo(p2);
        assertThat(p1.hashCode()).isEqualTo(p2.hashCode());
    }

    @Test
    void pointDTO_notEqualWhenDifferent() {
        PointDTO p1 = new PointDTO();
        p1.setX(1.0);
        p1.setY(2.0);

        PointDTO p2 = new PointDTO();
        p2.setX(9.0);
        p2.setY(2.0);

        assertThat(p1).isNotEqualTo(p2);
    }

    @Test
    void pointDTO_toString_containsFieldValues() {
        PointDTO point = new PointDTO();
        point.setX(5.0);
        point.setY(10.0);

        assertThat(point.toString()).contains("5.0").contains("10.0");
    }

    @Test
    void pointDTO_defaultsAreNull() {
        PointDTO point = new PointDTO();
        assertThat(point.getX()).isNull();
        assertThat(point.getY()).isNull();
    }

    // ── WallDTO ───────────────────────────────────────────────────────────────

    @Test
    void wallDTO_gettersAndSetters() {
        WallDTO wall = new WallDTO();
        wall.setX1(0.0);
        wall.setY1(0.0);
        wall.setX2(100.0);
        wall.setY2(0.0);

        assertThat(wall.getX1()).isEqualTo(0.0);
        assertThat(wall.getY1()).isEqualTo(0.0);
        assertThat(wall.getX2()).isEqualTo(100.0);
        assertThat(wall.getY2()).isEqualTo(0.0);
    }

    @Test
    void wallDTO_equalsAndHashCode() {
        WallDTO w1 = buildWall(0.0, 0.0, 100.0, 0.0);
        WallDTO w2 = buildWall(0.0, 0.0, 100.0, 0.0);

        assertThat(w1).isEqualTo(w2);
        assertThat(w1.hashCode()).isEqualTo(w2.hashCode());
    }

    @Test
    void wallDTO_notEqualWhenDifferent() {
        WallDTO w1 = buildWall(0.0, 0.0, 100.0, 0.0);
        WallDTO w2 = buildWall(0.0, 0.0, 200.0, 0.0);

        assertThat(w1).isNotEqualTo(w2);
    }

    @Test
    void wallDTO_toString_containsCoordinates() {
        WallDTO wall = buildWall(1.0, 2.0, 3.0, 4.0);
        String str = wall.toString();
        assertThat(str).contains("1.0").contains("2.0").contains("3.0").contains("4.0");
    }

    // ── WindowDTO ─────────────────────────────────────────────────────────────

    @Test
    void windowDTO_gettersAndSetters() {
        WindowDTO window = new WindowDTO();
        window.setX(10.0);
        window.setY(20.0);
        window.setWidth(1.5);
        window.setHeight(1.2);
        window.setDistanceFromFloor(0.9);

        assertThat(window.getX()).isEqualTo(10.0);
        assertThat(window.getY()).isEqualTo(20.0);
        assertThat(window.getWidth()).isEqualTo(1.5);
        assertThat(window.getHeight()).isEqualTo(1.2);
        assertThat(window.getDistanceFromFloor()).isEqualTo(0.9);
    }

    @Test
    void windowDTO_equalsAndHashCode() {
        WindowDTO w1 = buildWindow(5.0, 5.0, 1.0, 1.5, 0.8);
        WindowDTO w2 = buildWindow(5.0, 5.0, 1.0, 1.5, 0.8);

        assertThat(w1).isEqualTo(w2);
        assertThat(w1.hashCode()).isEqualTo(w2.hashCode());
    }

    @Test
    void windowDTO_notEqualWhenDistanceDiffers() {
        WindowDTO w1 = buildWindow(5.0, 5.0, 1.0, 1.5, 0.8);
        WindowDTO w2 = buildWindow(5.0, 5.0, 1.0, 1.5, 1.2);

        assertThat(w1).isNotEqualTo(w2);
    }

    @Test
    void windowDTO_toString_containsDimensions() {
        WindowDTO window = buildWindow(1.0, 2.0, 3.0, 4.0, 0.5);
        assertThat(window.toString()).contains("3.0").contains("4.0");
    }

    // ── DeviceDTO ─────────────────────────────────────────────────────────────

    @Test
    void deviceDTO_gettersAndSetters() {
        DeviceDTO device = new DeviceDTO();
        device.setId("dev-1");
        device.setName("Philips Hue");
        device.setPrice(49.99);
        device.setEcosystem("Zigbee");
        device.setProtocol("MQTT");
        device.setLumens(800);
        device.setRequiresPlug(true);
        device.setRangeRadius(10.0);
        device.setDeviceType("light");
        device.setMountType("ceiling");
        device.setFieldOfView(120.0);
        device.setPowerConsumption(9.0);
        device.setCommunicationFrequency("2.4GHz");
        device.setWidth(0.1);

        assertThat(device.getId()).isEqualTo("dev-1");
        assertThat(device.getName()).isEqualTo("Philips Hue");
        assertThat(device.getPrice()).isEqualTo(49.99);
        assertThat(device.getEcosystem()).isEqualTo("Zigbee");
        assertThat(device.getProtocol()).isEqualTo("MQTT");
        assertThat(device.getLumens()).isEqualTo(800);
        assertThat(device.getRequiresPlug()).isTrue();
        assertThat(device.getRangeRadius()).isEqualTo(10.0);
        assertThat(device.getDeviceType()).isEqualTo("light");
        assertThat(device.getMountType()).isEqualTo("ceiling");
        assertThat(device.getFieldOfView()).isEqualTo(120.0);
        assertThat(device.getPowerConsumption()).isEqualTo(9.0);
        assertThat(device.getCommunicationFrequency()).isEqualTo("2.4GHz");
        assertThat(device.getWidth()).isEqualTo(0.1);
    }

    @Test
    void deviceDTO_equalsAndHashCode() {
        DeviceDTO d1 = buildDevice("id-1", "Lock", 99.0);
        DeviceDTO d2 = buildDevice("id-1", "Lock", 99.0);

        assertThat(d1).isEqualTo(d2);
        assertThat(d1.hashCode()).isEqualTo(d2.hashCode());
    }

    @Test
    void deviceDTO_notEqualWhenIdDiffers() {
        DeviceDTO d1 = buildDevice("id-1", "Lock", 99.0);
        DeviceDTO d2 = buildDevice("id-2", "Lock", 99.0);

        assertThat(d1).isNotEqualTo(d2);
    }

    @Test
    void deviceDTO_toString_containsNameAndId() {
        DeviceDTO device = buildDevice("dev-xyz", "Smart Bulb", 25.0);
        assertThat(device.toString()).contains("dev-xyz").contains("Smart Bulb");
    }

    @Test
    void deviceDTO_requiresPlugDefaultIsNull() {
        DeviceDTO device = new DeviceDTO();
        assertThat(device.getRequiresPlug()).isNull();
    }

    // ── PlacedDeviceDTO ───────────────────────────────────────────────────────

    @Test
    void placedDeviceDTO_gettersAndSetters() {
        PointDTO coords = new PointDTO();
        coords.setX(5.0);
        coords.setY(10.0);

        DeviceDTO device = buildDevice("d1", "Router", 200.0);

        PlacedDeviceDTO placed = new PlacedDeviceDTO();
        placed.setCoordinates(coords);
        placed.setRotationAngle(45.0);
        placed.setDevice(device);

        assertThat(placed.getCoordinates()).isSameInstanceAs(coords);
        assertThat(placed.getRotationAngle()).isEqualTo(45.0);
        assertThat(placed.getDevice()).isSameInstanceAs(device);
    }

    @Test
    void placedDeviceDTO_equalsAndHashCode() {
        PointDTO coords = new PointDTO();
        coords.setX(1.0);
        coords.setY(2.0);

        PlacedDeviceDTO pd1 = new PlacedDeviceDTO();
        pd1.setCoordinates(coords);
        pd1.setRotationAngle(0.0);

        PlacedDeviceDTO pd2 = new PlacedDeviceDTO();
        pd2.setCoordinates(coords);
        pd2.setRotationAngle(0.0);

        assertThat(pd1).isEqualTo(pd2);
        assertThat(pd1.hashCode()).isEqualTo(pd2.hashCode());
    }

    @Test
    void placedDeviceDTO_notEqualWhenRotationDiffers() {
        PointDTO coords = new PointDTO();

        PlacedDeviceDTO pd1 = new PlacedDeviceDTO();
        pd1.setCoordinates(coords);
        pd1.setRotationAngle(0.0);

        PlacedDeviceDTO pd2 = new PlacedDeviceDTO();
        pd2.setCoordinates(coords);
        pd2.setRotationAngle(90.0);

        assertThat(pd1).isNotEqualTo(pd2);
    }

    // ── RoomDTO ───────────────────────────────────────────────────────────────

    @Test
    void roomDTO_gettersAndSetters() {
        RoomDTO room = new RoomDTO();
        room.setId("room-1");
        room.setSquareMeters(20.5);
        room.setWallType("concrete");

        PointDTO door = new PointDTO();
        door.setX(2.0);
        door.setY(0.0);

        room.setDoors(List.of(door));
        room.setWalls(List.of(buildWall(0.0, 0.0, 5.0, 0.0)));
        room.setWindows(List.of(buildWindow(3.0, 0.0, 1.2, 1.0, 0.9)));
        room.setPlugs(List.of(door));

        assertThat(room.getId()).isEqualTo("room-1");
        assertThat(room.getSquareMeters()).isEqualTo(20.5);
        assertThat(room.getWallType()).isEqualTo("concrete");
        assertThat(room.getDoors()).hasSize(1);
        assertThat(room.getWalls()).hasSize(1);
        assertThat(room.getWindows()).hasSize(1);
        assertThat(room.getPlugs()).hasSize(1);
    }

    @Test
    void roomDTO_equalsAndHashCode() {
        RoomDTO r1 = new RoomDTO();
        r1.setId("room-a");
        r1.setSquareMeters(15.0);

        RoomDTO r2 = new RoomDTO();
        r2.setId("room-a");
        r2.setSquareMeters(15.0);

        assertThat(r1).isEqualTo(r2);
        assertThat(r1.hashCode()).isEqualTo(r2.hashCode());
    }

    @Test
    void roomDTO_notEqualWhenIdDiffers() {
        RoomDTO r1 = new RoomDTO();
        r1.setId("bedroom");

        RoomDTO r2 = new RoomDTO();
        r2.setId("kitchen");

        assertThat(r1).isNotEqualTo(r2);
    }

    @Test
    void roomDTO_toString_containsId() {
        RoomDTO room = new RoomDTO();
        room.setId("bathroom");
        assertThat(room.toString()).contains("bathroom");
    }

    @Test
    void roomDTO_listFieldsDefaultToNull() {
        RoomDTO room = new RoomDTO();
        assertThat(room.getWalls()).isNull();
        assertThat(room.getDoors()).isNull();
        assertThat(room.getWindows()).isNull();
        assertThat(room.getPlugs()).isNull();
    }

    // ── SetupBuildDTO ─────────────────────────────────────────────────────────

    @Test
    void setupBuildDTO_gettersAndSetters() {
        SetupBuildDTO dto = new SetupBuildDTO();
        dto.setId("build-1");
        dto.setScale("1:50");
        dto.setMaxBudget(3000.0);
        dto.setTargetEcosystem("Apple HomeKit");

        RoomDTO room = new RoomDTO();
        room.setId("living");
        dto.setRooms(List.of(room));

        PlacedDeviceDTO placed = new PlacedDeviceDTO();
        dto.setDevices(List.of(placed));

        assertThat(dto.getId()).isEqualTo("build-1");
        assertThat(dto.getScale()).isEqualTo("1:50");
        assertThat(dto.getMaxBudget()).isEqualTo(3000.0);
        assertThat(dto.getTargetEcosystem()).isEqualTo("Apple HomeKit");
        assertThat(dto.getRooms()).hasSize(1);
        assertThat(dto.getDevices()).hasSize(1);
    }

    @Test
    void setupBuildDTO_equalsAndHashCode() {
        SetupBuildDTO d1 = new SetupBuildDTO();
        d1.setId("same-id");
        d1.setMaxBudget(500.0);

        SetupBuildDTO d2 = new SetupBuildDTO();
        d2.setId("same-id");
        d2.setMaxBudget(500.0);

        assertThat(d1).isEqualTo(d2);
        assertThat(d1.hashCode()).isEqualTo(d2.hashCode());
    }

    @Test
    void setupBuildDTO_notEqualWhenBudgetDiffers() {
        SetupBuildDTO d1 = new SetupBuildDTO();
        d1.setMaxBudget(100.0);

        SetupBuildDTO d2 = new SetupBuildDTO();
        d2.setMaxBudget(999.0);

        assertThat(d1).isNotEqualTo(d2);
    }

    @Test
    void setupBuildDTO_toString_containsId() {
        SetupBuildDTO dto = new SetupBuildDTO();
        dto.setId("setup-xyz");
        assertThat(dto.toString()).contains("setup-xyz");
    }

    @Test
    void setupBuildDTO_defaultFieldsAreNull() {
        SetupBuildDTO dto = new SetupBuildDTO();
        assertThat(dto.getId()).isNull();
        assertThat(dto.getScale()).isNull();
        assertThat(dto.getMaxBudget()).isNull();
        assertThat(dto.getTargetEcosystem()).isNull();
        assertThat(dto.getRooms()).isNull();
        assertThat(dto.getDevices()).isNull();
    }

    @Test
    void setupBuildDTO_emptyRoomsList() {
        SetupBuildDTO dto = new SetupBuildDTO();
        dto.setRooms(List.of());
        assertThat(dto.getRooms()).isEmpty();
    }

    // ── boundary/regression ───────────────────────────────────────────────────

    @Test
    void deviceDTO_negativePrice_isAccepted() {
        DeviceDTO device = new DeviceDTO();
        device.setPrice(-1.0);
        assertThat(device.getPrice()).isEqualTo(-1.0);
    }

    @Test
    void windowDTO_zeroDistanceFromFloor() {
        WindowDTO window = new WindowDTO();
        window.setDistanceFromFloor(0.0);
        assertThat(window.getDistanceFromFloor()).isEqualTo(0.0);
    }

    @Test
    void wallDTO_negativeCoordinates() {
        WallDTO wall = buildWall(-10.0, -20.0, -5.0, -15.0);
        assertThat(wall.getX1()).isEqualTo(-10.0);
        assertThat(wall.getY1()).isEqualTo(-20.0);
    }

    @Test
    void roomDTO_largeSquareMeters() {
        RoomDTO room = new RoomDTO();
        room.setSquareMeters(99999.99);
        assertThat(room.getSquareMeters()).isEqualTo(99999.99);
    }

    @Test
    void placedDeviceDTO_fullRotation360() {
        PlacedDeviceDTO placed = new PlacedDeviceDTO();
        placed.setRotationAngle(360.0);
        assertThat(placed.getRotationAngle()).isEqualTo(360.0);
    }

    @Test
    void deviceDTO_lumensZero() {
        DeviceDTO device = new DeviceDTO();
        device.setLumens(0);
        assertThat(device.getLumens()).isEqualTo(0);
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    private WallDTO buildWall(double x1, double y1, double x2, double y2) {
        WallDTO wall = new WallDTO();
        wall.setX1(x1);
        wall.setY1(y1);
        wall.setX2(x2);
        wall.setY2(y2);
        return wall;
    }

    private WindowDTO buildWindow(double x, double y, double width, double height, double distanceFromFloor) {
        WindowDTO window = new WindowDTO();
        window.setX(x);
        window.setY(y);
        window.setWidth(width);
        window.setHeight(height);
        window.setDistanceFromFloor(distanceFromFloor);
        return window;
    }

    private DeviceDTO buildDevice(String id, String name, double price) {
        DeviceDTO device = new DeviceDTO();
        device.setId(id);
        device.setName(name);
        device.setPrice(price);
        return device;
    }
}