aws.s3.access-key=dummy-access-key
aws.s3.secret-key=dummy-secret-key
aws.s3.region=eu-central-1
aws.s3.bucket=dummy-bucket-name
#aws.s3.access-key=${AWS_ACCESS_KEY}
#aws.s3.secret-key=${AWS_SECRET_KEY}
#aws.s3.region=${AWS_REGION:eu-central-1}
#aws.s3.bucket=${AWS_S3_BUCKET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.codec.max-in-memory-size=12MB
server.tomcat.max-http-form-post-size=15MB



spring.application.name=SmartHouseBuilder
server.port=20025
spring.profiles.active=dev

jwt.secret=AcesastaEsteOCheieSecretaMultMaiLungaSiSiguraPentruAplicatiaMea1234567890!
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=2592000000

app.rate-limit.capacity=10
app.rate-limit.minutes=1

app.base-url=http://localhost:20025
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-2.5-flash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
app.mail.from=noreply@smarthousebuilder.com
spring.security.oauth2.client.registration.google.client-id=dummy-id
spring.security.oauth2.client.registration.google.client-secret=dummy-secret
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com
spring.datasource.url=jdbc:postgresql://database-1-instance-1.c9uscu6yo67l.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=database-1-instance-1.c9uscu6yo67l.eu-north-1.rds.amazonaws.com:5432/?Action=connect&DBUser=postgres&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAZXOTZD5RXX4JTRO5%2F20260526%2Feu-north-1%2Frds-db%2Faws4_request&X-Amz-Date=20260526T142744Z&X-Amz-Expires=900&X-Amz-Security-Token=IQoJb3JpZ2luX2VjELb%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmV1LW5vcnRoLTEiRzBFAiBI785fPFhkXcXF5Hs0vC9bd875DWPlHpQcPGrKR9OtkAIhAI70CEuOWi6Bh5dNZZmtey3LEtCudjaOUMYaA1eA7yi9KvoCCID%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMNjY4ODQ4NDMwOTQ3IgwCD08B%2B%2Bv5Bp7z%2BNkqzgJ6NlOaUzZAmvI1fSyr4aPH%2Fczbdn6azHipnoYi%2Bb6gAUw1EW9d15ln%2Fd4sGFk%2BDQ3Lid529rDbN9reUCfiXZr7lrNyoZIDyRWLzhIJlqO3ZGtPfmyMC8o8K9i1XEKRMdQV2%2FH7xHSJHXnfy5vsebozLoBQWesof6tmdLZ1rUbmSiS%2F%2FTYbglY0nP1uWU5IDULVnqC7uBa%2Fs8SWRDMnWZCegkX1hOCoQzBp7WcUgA2hvAVrjNgcMHX5D5foD0GNwWmcj46MMGmtiRbo6ubWr4xhzINctO14CH%2FEzrcNFQ2U9oJPk03bWDpOfRP3UxJjFIXkWkdcKYSKS7N0Yw5UUVZenX4BYxEIjt5yyuZKMuhqSGEkp1FSeRwm8HEaXeAUwbYSSdzSY0htlgwYA%2BM48YawsXmgZ81nLZk4LhNLx%2FY6%2Bx%2FtKcWA%2BpGAom6uWYnlMIjF1tAGOq0C2wN7vUMvaFfDB9SR25ccrPsjjOP%2BGGnnrnFdWQM4xOSSgsHPqFu7kDtDWYUyrO4Jywiwvg49wsMsJ3NWqSkV0axG8%2FVcu1S4DkBLQYg%2BgeTV%2FQBojLmvze0MlkUaOr%2FtcbTxknjaJ4cjjH4hgciwOUoTeW%2BOqEqtTKda77AlLyG6D%2BlL%2BtvBsLkVlldMBCCjOGclLUms9tBtZGg4FWJ1l6pj%2F%2Bra%2B1gEItlHUIKxJPg91MGKrW0otqjKCqgoauvlV9hEJR7%2B1hcJvejoKl24uVFm3nmGK816%2BUGC87ZyMYJ3Ug9QEe82Yed6kgluco0%2FQCLKkYAzrDqoeTye4zPMMAoOIHWLe2dVyjDwDW3C0qKvI9GKg7LyQxqKsMtmMwCPrXBlfO40r1Sgp8mRdQ%3D%3D&X-Amz-Signature=48b9414c15fa3a8f168e4622a63def7b76b01733114ccc92f455c3d71247bceb&X-Amz-SignedHeaders=host
#spring.datasource.url=jdbc:postgresql://localhost:5432/Scrapper
#spring.datasource.username=postgres
#spring.datasource.password=andreidecenu45
spring.datasource.driver-class-name=org.postgresql.Driver