
#aws.s3.access-key=${AWS_ACCESS_KEY}
#aws.s3.secret-key=${AWS_SECRET_KEY}
#aws.s3.region=${AWS_REGION:eu-central-1}
#aws.s3.bucket=${AWS_S3_BUCKET}
aws.s3.access-key=${AWS_ACCESS_KEY:dummy}
aws.s3.secret-key=${AWS_SECRET_KEY:dummy}
aws.s3.region=${AWS_REGION:eu-central-1}
aws.s3.bucket=${AWS_S3_BUCKET:dummy}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.codec.max-in-memory-size=12MB
server.tomcat.max-http-form-post-size=15MB

spring.application.name=SmartHouseBuilder
server.port=20025
spring.profiles.active=dev

jwt.secret=AcesastaEsteOCheieSecretaMultMaiLungaSiSiguraPentruAplicatiaMea1234567890!
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=2592000000

app.rate-limit.capacity=10
app.rate-limit.minutes=1

app.base-url=http://localhost:20025
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-2.5-flash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
app.mail.from=noreply@smarthousebuilder.com
spring.security.oauth2.client.registration.google.client-id=dummy-id
spring.security.oauth2.client.registration.google.client-secret=dummy-secret
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

scraper.feed.url.rovision=${SCRAPER_ROVISION_URL:}
scraper.feed.url.casesmart=${SCRAPER_CASESMART_URL:}
scraper.feed.url.vonmag=${SCRAPER_VONMAG_URL:}

spring.datasource.url=jdbc:postgresql://database-1-instance-1.c9uscu6yo67l.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=database-1-instance-1.c9uscu6yo67l.eu-north-1.rds.amazonaws.com:5432/?Action=connect&DBUser=postgres&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAZXOTZD5RUF34KR6L%2F20260527%2Feu-north-1%2Frds-db%2Faws4_request&X-Amz-Date=20260527T131508Z&X-Amz-Expires=900&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEM3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmV1LW5vcnRoLTEiSDBGAiEAj2aGzzy9xhrjPgKH8Ne4yWg94jud7dLjEOzfEmZhubMCIQDwFj%2F1feeiT%2BRDZBf8OTQX4NgJ3%2BYiv6FOVZJkniNa%2Bir6AgiW%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDY2ODg0ODQzMDk0NyIM%2BP1uIrZfFwtwaij9Ks4Cb0T9ZBCUAyAvZ2G6QlJhJqHsuQhZZMwSIJRuu%2BEZx%2B5Vftg723mdmsLweFfPeGJ%2FJYz7FvjoZEEvubUehfTVm1F9Jewy6ICLFZ4nQdQbHhR7oSWL7BzD0y2uDK0EpSQULfjB9z7i4NZZ%2BlQpwmOGvUVqLdgJfvvdYXkqRPnXhMmLe2DjWFtb85%2BdjX9%2BOP4TBgyX%2BohX6wQGmb63Fiyp6nOdi21IaLcdLOgdbxthE1Jb9ChQEeIpq7w%2FVdRqwi243tVLzt5POdeH9GLfchCGFGZa7HHhFObyAK2cNj6q0Ky3FxWE%2BkTakXCin8nGPLtL3wfr4Mel5kgymtLw399xXHTPmXRE4SZq8jJubpnBIwuVUtFV1xHlrXPNDa4XZDeN7Oe3yKKwXeEW%2FmZK4eWhWBtB6ltjSuF5aiSaoTI1v4UQp6woKdyz0fCZhUiWbjC83NvQBjqsAhCjDIfnwOgBCvl356SZrvHaEcbPO%2Bz4RN9GP76EC2myDWZYFMnMnWLj8CepEg9ijwycCsmhMLNXqfbGwOKNHaDpQL6aj0fxtlIPPKfh6z%2BZdH8tYUZ%2Bv%2FJnpbPVhqdeZ0F02ZJHHZNaXLoKZ4c0KUWHqVxh0rkKVg3oyvW2sA%2B%2BdMXUmOFcibOzlYFvyEbGMMiCrhHeO9ivwQ%2B13Lz8tpntYkBWAQsZlvWt62vVqDaFVyHBgwrp6Xe%2FV%2BL33X%2BKQuidsClUDc7Yyhl9J5cDIlf9wPknK%2FAOE9%2FguP33rHT45wx7trkuEdow7zP501ls5ZFWaN0HJonWqbo8gv1ZdSmg7Ap6eUcV89P9%2FcABwJH2DEmvRJrPryG4MNsUSoZcrBfDuWb3qgMh3%2B2c%2BQ%3D%3D&X-Amz-Signature=079392f79cab6eaaf131dd9722d395d3e1e1c0d8afceba139066072532609f38&X-Amz-SignedHeaders=host
spring.datasource.driver-class-name=org.postgresql.Driver