spring.application.name=SmartHouseBuilder
server.port=20025
spring.profiles.active=dev

jwt.secret=AcesastaEsteOCheieSecretaMultMaiLungaSiSiguraPentruAplicatiaMea1234567890!
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=2592000000

app.rate-limit.capacity=10
app.rate-limit.minutes=1

app.base-url=http://localhost:20025

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
app.mail.from=noreply@smarthousebuilder.com
spring.security.oauth2.client.registration.google.client-id=dummy-id
spring.security.oauth2.client.registration.google.client-secret=dummy-secret
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com